version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: cobot-pro-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cobot_pro
      MYSQL_USER: cobot
      MYSQL_PASSWORD: cobotpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data:
