import type { LoaderFunctionArgs, MetaFunction } from "@remix-run/node";
import { json, redirect } from "@remix-run/node";
import { setupVercelDatabase } from "~/utils/vercel-db-setup.server";
import { Form, Link, useLoaderData } from "@remix-run/react";

export const meta: MetaFunction = () => [{ title: "Upsell Pro - Shopify App" }];

export async function loader({ request }: LoaderFunctionArgs) {
  // For Vercel deployment, set up the database
  if (process.env.NODE_ENV === 'production') {
    try {
      await setupVercelDatabase();
    } catch (error) {
      console.error('Error setting up database:', error);
      // Continue anyway, as we don't want to block the landing page
    }
  }

  // Check if there's a shop parameter in the URL
  const url = new URL(request.url);
  const shop = url.searchParams.get("shop");

  // Check if we should redirect to the app
  // This is useful for users who are already logged in
  // or for redirecting from the root to the app
  const redirectToApp = url.searchParams.get("redirect") === "app";

  if (redirectToApp && shop) {
    return redirect(`/app?shop=${shop}`);
  }

  return json({ shop });
}

export default function Index() {
  const { shop } = useLoaderData<typeof loader>();

  return (
    <main className="relative min-h-screen bg-white">
      <div className="bg-blue-600 text-white py-16">
        <div className="container mx-auto px-4 max-w-6xl">
          <div className="flex flex-col md:flex-row items-center justify-between">
            <div className="md:w-1/2 mb-10 md:mb-0">
              <h1 className="text-4xl md:text-5xl font-bold mb-4">Upsell Pro</h1>
              <p className="text-xl md:text-2xl mb-8">Boost your store's revenue with smart upsell offers</p>
              <p className="text-lg mb-6">Automatically suggest relevant products to your customers at the perfect moment in their shopping journey.</p>

              {shop ? (
                <Link
                  to={`/auth?shop=${shop}`}
                  className="inline-block bg-white text-blue-600 font-bold py-3 px-6 rounded-lg shadow-lg hover:bg-blue-50 transition duration-200"
                >
                  Install App
                </Link>
              ) : (
                <Form method="get" action="/auth" className="flex">
                  <input
                    type="text"
                    name="shop"
                    placeholder="your-store.myshopify.com"
                    className="py-3 px-4 rounded-l-lg w-64 text-gray-800 focus:outline-none"
                    required
                  />
                  <button
                    type="submit"
                    className="bg-white text-blue-600 font-bold py-3 px-6 rounded-r-lg hover:bg-blue-50 transition duration-200"
                  >
                    Install App
                  </button>
                </Form>
              )}
            </div>

            <div className="md:w-1/2">
              <img
                src="https://cdn.shopify.com/s/files/1/0533/2089/files/shopify-online-store_1400x.jpg?v=1620253416"
                alt="Shopify Store with Upsell"
                className="rounded-lg shadow-xl"
              />
            </div>
          </div>
        </div>
      </div>

      <div className="py-16 container mx-auto px-4 max-w-6xl">
        <h2 className="text-3xl font-bold text-center mb-12">How Upsell Pro Works</h2>

        <div className="grid md:grid-cols-3 gap-8">
          <div className="bg-gray-50 p-6 rounded-lg">
            <div className="text-4xl mb-4 text-blue-600">1</div>
            <h3 className="text-xl font-semibold mb-2">Create Upsell Offers</h3>
            <p>Define which products should trigger upsell offers and what complementary products to suggest.</p>
          </div>

          <div className="bg-gray-50 p-6 rounded-lg">
            <div className="text-4xl mb-4 text-blue-600">2</div>
            <h3 className="text-xl font-semibold mb-2">Customize Appearance</h3>
            <p>Choose where and how your upsell offers appear to customers for maximum impact.</p>
          </div>

          <div className="bg-gray-50 p-6 rounded-lg">
            <div className="text-4xl mb-4 text-blue-600">3</div>
            <h3 className="text-xl font-semibold mb-2">Track Performance</h3>
            <p>Monitor conversion rates and additional revenue generated by your upsell campaigns.</p>
          </div>
        </div>
      </div>

      <div className="bg-gray-50 py-16">
        <div className="container mx-auto px-4 max-w-6xl">
          <h2 className="text-3xl font-bold text-center mb-12">Features</h2>

          <div className="grid md:grid-cols-2 gap-8">
            <div className="flex items-start">
              <div className="bg-blue-600 text-white p-3 rounded-full mr-4">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
              </div>
              <div>
                <h3 className="text-xl font-semibold mb-2">Smart Product Recommendations</h3>
                <p>Suggest relevant products based on what's in the customer's cart.</p>
              </div>
            </div>

            <div className="flex items-start">
              <div className="bg-blue-600 text-white p-3 rounded-full mr-4">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
              </div>
              <div>
                <h3 className="text-xl font-semibold mb-2">Multiple Display Options</h3>
                <p>Show offers as popups, inline suggestions, or in the cart.</p>
              </div>
            </div>

            <div className="flex items-start">
              <div className="bg-blue-600 text-white p-3 rounded-full mr-4">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
              </div>
              <div>
                <h3 className="text-xl font-semibold mb-2">Discount Offers</h3>
                <p>Entice customers with special discounts on upsell products.</p>
              </div>
            </div>

            <div className="flex items-start">
              <div className="bg-blue-600 text-white p-3 rounded-full mr-4">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
              </div>
              <div>
                <h3 className="text-xl font-semibold mb-2">Detailed Analytics</h3>
                <p>Track impressions, clicks, conversions, and additional revenue.</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <footer className="bg-gray-800 text-white py-12">
        <div className="container mx-auto px-4 max-w-6xl">
          <div className="flex flex-col md:flex-row justify-between items-center">
            <div className="mb-6 md:mb-0">
              <h2 className="text-2xl font-bold">Upsell Pro</h2>
              <p className="mt-2">Boost your Shopify store's revenue today.</p>
            </div>

            <div>
              {shop ? (
                <Link
                  to={`/auth?shop=${shop}`}
                  className="inline-block bg-blue-600 text-white font-bold py-3 px-6 rounded-lg hover:bg-blue-700 transition duration-200"
                >
                  Install App
                </Link>
              ) : (
                <Link
                  to="#top"
                  onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
                  className="inline-block bg-blue-600 text-white font-bold py-3 px-6 rounded-lg hover:bg-blue-700 transition duration-200"
                >
                  Get Started
                </Link>
              )}
            </div>
          </div>

          <div className="mt-8 pt-8 border-t border-gray-700 text-center text-gray-400">
            <p>&copy; {new Date().getFullYear()} Upsell Pro. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </main>
  );
}
